version: "3.7"
services:
  elasticsearch:
    image: elasticsearch:7.6.0
    container_name: elasticsearch
    init: true
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
  web:
    image: php:7.4-fpm
    container_name: web
    init: true
    working_dir: /var/www
    volumes:
      - .:/var/www
    env_file:
      - .env.app
  nginx:
    image: nginx:1.17.8
    container_name: nginx
    init: true
    volumes:
      - .:/var/www
      - ./server.conf:/etc/nginx/conf.d/default.conf
    ports:
      - ${WEB_EXPOSED_PORT}:80
